#! /bin/sh

Clock() {
        DATETIME=$(date "+%a %b %d, %T")
        echo -e "$DATETIME"
}

Vol() {
	volLevel=$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/%.*//g')
	echo -e "$volLevel"
}

Bspw() {
	echo -e $(bspc query -D -d)
}

bgcolor="$(xrdb -query | grep background | tail -c 8)"
fgcolor="$(xrdb -query | grep foreground | tail -c 8)"
lemon=.config/lemonbar/io
height=30

trap 'bspc config top_padding 0' INT TERM QUIT EXIT

bspc config top_padding $height

while true; do
	echo "%{F$fgcolor}%{B$bgcolor} %{l}$(Bspw)%{c}$(Clock)%{r}$(Vol)"
	sleep 0.1
done
