#! /bin/zsh

sxhkd -m -1 &

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner
bspc config top_padding 33
bspc config initial_polarity second_child

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^1
bspc rule -a vim desktop=^2
bspc rule -a Skype desktop=^3
bspc rule -a qTox desktop=^3
bspc rule -a ncmpcpp desktop=^4
bspc rule -a spotify desktop=^4
bspc rule -a Steam desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a dota2 desktop=^6
bspc rule -a FTL desktop=^6
bspc rule -a csgo_linux64 desktop=^6
bspc rule -a hl2_linux desktop=^6
bspc rule -a ranger desktop=^8
bspc rule -a Gimp desktop=^10
bspc rule -a mpv state=floating sticky=on
bspc rule -a Galculator state=floating sticky=on
bspc rule -a "Android Emulator" state=floating
bspc rule -a "Peek" state=floating
bspc rule -a steam state=floating follow=off focus=off

bspc rule -a Plank layer=normal manage=on border=off focus=off locked=on

bspc config normal_border_color '#000000'
bspc config focused_border_color '#FFFFFF'

touch $HOME/.dbus/Xdbus
chmod 600 $HOME/.dbus/Xdbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus

# interface
#$HOME/.scripts/xwinwrap.sh ~/Pictures/Wallpapers/animated/security-window.gif &> /dev/null &!
$HOME/.scripts/lock.sh --off --allow-blanking &!
polybar -r legacy &!
compton --config ~/.config/compton/compton.conf --dbus &!
steam-native &!
qtox &!
#sleep 10; ~/.scripts/start-conkies.sh &!
