#! /bin/zsh

sxhkd -m -1 &

bspc config border_width        5
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^1
bspc rule -a vim desktop=^2
bspc rule -a Skype desktop=^3
bspc rule -a ncmpcpp desktop=^4
bspc rule -a spotify desktop=^4
bspc rule -a Steam desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a dota2 desktop=^6
bspc rule -a FTL desktop=^6
bspc rule -a csgo_linux desktop=^6
bspc rule -a hl2_linux desktop=^6
bspc rule -a SkullGirls.x86_64-pc-linux-gn desktop=^6
bspc rule -a Ranger desktop=^8
bspc rule -a mpv state=floating sticky=on

#bspc rule -a Plank layer=above manage=on border=off focus=off locked=on
bspc rule -a Plank layer=normal manage=on border=off focus=off locked=on

#violet
#bspc config active_border_color '#312e3d'
#bspc config normal_border_color '#312e3d'
#bspc config focused_border_color '#59507b'

#pink/dark green
bspc config active_border_color '#21324d'
bspc config normal_border_color '#21324d'
bspc config focused_border_color '#8ca1c2'

exec ~/.config/bspwm/startup.sh &
