#! /bin/zsh

sxhkd -m -1 &

bspc config border_width        1
bspc config window_gap          15

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Firefox desktop=^1
bspc rule -a vim desktop=^2
bspc rule -a qTox desktop=^3
bspc rule -a ncmpcpp desktop=^4
bspc rule -a spotify desktop=^4
bspc rule -a Steam desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a dota2 desktop=^6
bspc rule -a FTL desktop=^6
bspc rule -a csgo_linux64 desktop=^6
bspc rule -a hl2_linux desktop=^6
bspc rule -a ranger desktop=^8
bspc rule -a Thunderbird desktop=^9
bspc rule -a Gimp desktop=^10
bspc rule -a mpv state=floating sticky=on
bspc rule -a Galculator state=floating sticky=on
bspc rule -a "Android Emulator" state=floating
bspc rule -a "Peek" state=floating
bspc rule -a steam state=floating follow=off focus=off

bspc rule -a Plank layer=normal manage=on border=off focus=off locked=on

bspc config active_border_color '#364559'
bspc config normal_border_color '#2F3A50'
bspc config focused_border_color '#cccccc'

touch $HOME/.dbus/Xdbus
chmod 600 $HOME/.dbus/Xdbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus

# interface
polybar legacy &!
bspc config top_padding 24
compton --config ~/.config/compton/compton.conf --dbus &!
sleep 10; ~/.scripts/start-conkies.sh &!

sleepfor=2;
# apps
qtox &!
/home/lukas/.scripts/betterlockscreen/lock.sh -u $(cat ~/.fehbg | tail -n 1 | awk '{print $3}' | sed "s/'//gi") &!
xautolock -time 1 -locker '/home/lukas/.scripts/betterlockscreen/lock.sh -l' &!
sleep $sleepfor; thunderbird &!
sleep $sleepfor; apulse firefox &!
sleep $sleepfor; slack &!
sleep $sleepfor; apulse spotify &!
sleep $sleepfor; force-move.sh Slack 2 &!
sleep $sleepfor; force-move.sh Spotify 3 &!

sleep $sleepfor; xmodmap -e 'clear lock'
sleep $sleepfor; xmodmap -e 'keycode 0x42 = Escape'
sleep $sleepfor; xmodmap ~/.Xmodmap
